"$schema" = "./node_modules/wrangler/config-schema.json"

name = "lovelyseaviewapartments"
compatibility_date = "2026-05-31"
pages_build_output_dir = "out"

[assets]
directory = "./out"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
